### ISSUE TITLE
Unable to draw vertical line with line/5

### ISSUE THREAD

**Issue by jjcarstens** [pappersverk/oled#2]
I was attempting to draw a vertical line, specifying the start and end coordinates via `line/5`, but it fails with a bad arithmetic expression error:

```
iex(12)> Playground.Display.line(64, 8, 64, 24)
** (exit) exited in: GenServer.call(Playground.Display, {:line, 64, 8, 64, 24, []}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArithmeticError) bad argument in arithmetic expression
            (oled) lib/oled/display/impl/ssd_1306/draw.ex:69: anonymous fn/7 in OLED.Display.Impl.SSD1306.Draw.line/6
            (oled) lib/oled/display/server.ex:113: OLED.Display.Server.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:1009: GenServer.call/3
```

Which makes sense because [this line](https://github.com/pappersverk/oled/blob/master/lib/oled/display/impl/ssd_1306/draw.ex#L69) is doing the calculation and when there is no delta-y, it attempts `0/0` which breaks things

```
iex(15)> trunc 8 + 16 * (64-64)/0              
** (ArithmeticError) bad argument in arithmetic expression: 0 / 0
    :erlang./(0, 0)
```

I can get around this with `line_v/4`, but just thought I'd put this here if it was something to fix (or until I can get around to maybe help fix)

**Comment by luisgabrielroldan** [comment]
Thanks @jjcarstens !

I just created this #3 to fix the issue.
Now the `line` function uses internally `line_v` or `line_h` as those are optimized for this cases.

I added a couple of tests. It would be great if you have the opportunity to test fix.
