### ISSUE TITLE
Error on display start when no i2c device is present

### ISSUE THREAD

**Issue by jjcarstens** [pappersverk/oled#4]
In a situation where you attempt to start a display (in my case, via i2c), but the device is not communicating for some reason, it throws an error and crashes the whole process:

```elixir
# There is no i2c deice attached
iex(1)> Playground.Display.start_link()
{:error,
 {:function_clause,
  [
    {OLED.Display.Impl.SSD1306, :clear_buffer,
     [{:error, {:cmd, 174, {:error, :i2c_nak}}}, :off],
     [file: 'lib/oled/display/impl/ssd_1306.ex', line: 163]},
    {OLED.Display.Impl.SSD1306, :initialize, 1,
     [file: 'lib/oled/display/impl/ssd_1306.ex', line: 90]},
    {OLED.Display.Impl, :init, 1, [file: 'lib/oled/display/impl.ex', line: 14]},
    {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]},
    {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]},
    {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
  ]}}
** (EXIT from #PID<0.2588.0>) shell process exited with reason: an exception was raised:
    ** (FunctionClauseError) no function clause matching in OLED.Display.Impl.SSD1306.clear_buffer/2
        (oled) lib/oled/display/impl/ssd_1306.ex:163: OLED.Display.Impl.SSD1306.clear_buffer({:error, {:cmd, 174, {:error, :i2c_nak}}}, :off)
        (oled) lib/oled/display/impl/ssd_1306.ex:90: OLED.Display.Impl.SSD1306.initialize/1
        (oled) lib/oled/display/impl.ex:14: OLED.Display.Impl.init/1
        (stdlib) gen_server.erl:374: :gen_server.init_it/2
        (stdlib) gen_server.erl:342: :gen_server.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

Tracking it down a bit shows that there is no function clause for [this private `command` function](https://github.com/pappersverk/oled/blob/master/lib/oled/display/impl/ssd_1306.ex#L256) and there is no matching clause because  [this command](https://github.com/pappersverk/oled/blob/master/lib/oled/display/impl/ssd_1306.ex#L105) to turn the display off fails and every subsequent command is ignored, but the error is still passed to the `clear_buffer/2` private function which doesn't know how to skip past failed commands.

Imo, I don't think there needs to be a lot of fancy work around for dealing with devices not attached and we can let things fail, but I do think a more helpful error might be nice. Or just to be a little more consistent (i.e. if the command flow knows how to ignore the error, and reset/transfer/etc, then the other handling functions probably need to ignore it as well)

Not really crucial for me right now, but just wanted to document

**Comment by luisgabrielroldan** [comment]
Quick fix merged (#5). Thanks!
