### ISSUE TITLE
Feature Request: Fake screen for testing/development/web-preview

### ISSUE THREAD

**Issue by PhillippOhlandt** [pappersverk/oled#8]
Hey,

I noticed that there is no implementation of a fake screen in case the user does not run the code on the target hardware, i.e. while developing locally. 

A fake screen instance would also enable cool things like a simple liveview preview (saw that on @lawik 's livestream but with the Inky lib).

Is something like that planned?

**Comment by lawik** [comment]
I don't think there are any plans for more festires in this library right now. 

At one point I had any idea for a common API for these simpler screens (this and Inky so far) to share that type of tooling.

If you want to make one as an optional extra library you are free to. inky_host_dev uses wx to provide something like that for inky.

I haven't checked this libraries internals so I don't know if it has the separation to support something like that in there now.

I didn't write this but am part of the folks who bundled it under Pappersverk :D

**Comment by PhillippOhlandt** [comment]
@lawik Hey, I had a look before posting this and right now it's not possible to externally extend it the way I would prefer such a solution (just changing the device or driver config setting which would allow easy config via host.exs and target.exs).

Of course, one could write a simple GenServer with the same API as this and build custom logic to decide when to start it.
